language: ruby
rvm:
  - 2.4.1
services:
  - postgresql
env:
  - RAILS_ENV=test
script:
  - RAILS_ENV=test bundle exec rails db:create
  - RAILS_ENV=test bundle exec rails db:migrate --trace
  - bundle exec rspec spec/
