version: "2"
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${SALAYO_DATABASE_NAME}"
      POSTGRES_PASSWORD: "${SALAYO_DATABASE_PASSWORD}"
    volumes:
      - ./sql:/sql
